### ISSUE TITLE
Feature request: keyCode accept string as argument

### ISSUE THREAD

**Issue by gengjiawen** [Dafrok/react-shortcut-key#1]
The keymap dict can be find here : https://github.com/wesbos/keycodes/blob/gh-pages/scripts.js. With this feature, the api will be much more intuitive.

**Comment by Dafrok** [comment]
Pretty good idea, next version is coming soon :)

**Comment by gengjiawen** [comment]
That's will be really nice.
By the way, why the latest commit time is 2017 December...

**Comment by Dafrok** [comment]
So sad about that, my system clock has been broken last year...

**Comment by Dafrok** [comment]
New version & documentation has arrived, enjoy it.

> https://dafrok.github.io/react-shortcut-key/
