### ISSUE TITLE
After click button, hotkey no longer working

### ISSUE THREAD

**Issue by gengjiawen** [Dafrok/react-shortcut-key#3]
Reproduction: check the https://github.com/gengjiawen/react-shortcut-key example folder.
* Before you click the hi button in top, shortcut works fine.
* After click the button, shortcut will break.
* Click other area in this page, it will work again.

I find a fix, in React Component 
```
  componentDidUpdate = () => {
    console.log(this);
    document.activeElement.blur()
  }
```
But I can't figure out the reason why this occur.

**Comment by Dafrok** [comment]
It's a feature however. Browsers has its own shortcut keys act on some elements, such as `<button>` or `<input>`. Imagine the case if the browser is focusing on an `<input>` element, and then you press `ctrl + v`, what will happen? It's no doubt there will be a conflict. So I prefer preventing keyborad events on these element to resolve this problem.

**Comment by Dafrok** [comment]
The crtical line is here https://github.com/Dafrok/react-shortcut-key/blob/master/src/index.js#L127

**Comment by Dafrok** [comment]
By the way, I find the key of keymap is meaningless at all. Being the only user of my lib, how do you think If I change the API like this in 2.0 version?

```javascript
// Before
const keymap = {
  hello: {
    key: 'enter',
    ctrl: true,
    fn: componentOnHello
  }
}

// After
const keymap = {
  'ctrl+enter': componentOnHello
}
```

**Comment by Dafrok** [comment]
Hmmm, I think it will be good. 2.0 version has been released. Check the documentation plz.

> https://github.com/Dafrok/react-shortcut-key/blob/master/README.md

**Comment by gengjiawen** [comment]
I think this issue should be mentioned in README.md.

I have upgrade to 2.0.2, works fine :)

**Comment by Dafrok** [comment]
OK, just remember you have to prevent default key events by yourself in 2.0 if needed.

**Comment by gengjiawen** [comment]
And put the demo link and License info in README.md will be more user friendly.

**Comment by Dafrok** [comment]
Finished :)
